version: "3.8"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    env_file: .env
    volumes:
      - /var/lib/mysql
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: $API_DB_USER_ROOT
      MYSQL_DATABASE: $API_DB_DATABASE
      MYSQL_USER: $API_DB_USER
      MYSQL_PASSWORD: $API_DB_PASSWORD
      MYSQL_PORT: $API_DB_PORT
    ports:
      - "3306:3306"
    expose:
      - '3306'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
